services:
  rabbitmq:
    image: rabbitmq
    command: rabbitmq-server
    ports:
      - 5672:5672
    expose:
      - "5672"
      - "15672"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "5672"]
      interval: 10s
      timeout: 10s
      retries: 5